name: Release instrumentation.dylib

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload_release_asset:
    name: Upload instrumentation.dylib to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: instrumentation.dylib
